/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QFrame *frame;
    QPushButton *btn_1;
    QPushButton *btn_2;
    QPushButton *btn_3;
    QPushButton *btn_4;
    QPushButton *btn_5;
    QPushButton *btn_6;
    QPushButton *btn_7;
    QPushButton *btn_8;
    QPushButton *btn_17;
    QPushButton *btn_18;
    QPushButton *btn_19;
    QPushButton *btn_20;
    QPushButton *btn_21;
    QPushButton *btn_22;
    QPushButton *btn_23;
    QPushButton *btn_24;
    QPushButton *btn_25;
    QPushButton *btn_26;
    QPushButton *btn_27;
    QPushButton *btn_28;
    QPushButton *btn_29;
    QPushButton *btn_30;
    QPushButton *btn_31;
    QPushButton *btn_32;
    QPushButton *btn_33;
    QPushButton *btn_34;
    QPushButton *btn_35;
    QPushButton *btn_36;
    QPushButton *btn_37;
    QPushButton *btn_38;
    QPushButton *btn_39;
    QPushButton *btn_40;
    QPushButton *btn_41;
    QPushButton *btn_42;
    QPushButton *btn_43;
    QPushButton *btn_44;
    QPushButton *btn_45;
    QPushButton *btn_46;
    QPushButton *btn_47;
    QPushButton *btn_48;
    QPushButton *btn_49;
    QPushButton *btn_50;
    QPushButton *btn_51;
    QPushButton *btn_52;
    QPushButton *btn_53;
    QPushButton *btn_54;
    QPushButton *btn_55;
    QPushButton *btn_56;
    QPushButton *btn_57;
    QPushButton *btn_58;
    QPushButton *btn_59;
    QPushButton *btn_60;
    QPushButton *btn_61;
    QPushButton *btn_62;
    QPushButton *btn_63;
    QPushButton *btn_64;
    QPushButton *btn_65;
    QPushButton *btn_66;
    QPushButton *btn_67;
    QPushButton *btn_68;
    QPushButton *btn_69;
    QPushButton *btn_70;
    QPushButton *btn_71;
    QPushButton *btn_72;
    QFrame *frame_2;
    QPushButton *btn_73;
    QPushButton *btn_74;
    QPushButton *btn_75;
    QPushButton *btn_76;
    QPushButton *btn_77;
    QPushButton *btn_78;
    QPushButton *btn_79;
    QPushButton *btn_80;
    QPushButton *btn_81;
    QPushButton *btn_82;
    QPushButton *btn_83;
    QPushButton *btn_84;
    QPushButton *btn_85;
    QPushButton *btn_86;
    QPushButton *btn_87;
    QPushButton *btn_88;
    QPushButton *btn_89;
    QPushButton *btn_90;
    QPushButton *btn_91;
    QPushButton *btn_92;
    QPushButton *btn_93;
    QPushButton *btn_94;
    QPushButton *btn_95;
    QPushButton *btn_96;
    QPushButton *btn_97;
    QPushButton *btn_98;
    QPushButton *btn_99;
    QPushButton *btn_100;
    QPushButton *btn_101;
    QPushButton *btn_102;
    QPushButton *btn_103;
    QPushButton *btn_104;
    QPushButton *btn_105;
    QPushButton *btn_106;
    QPushButton *btn_107;
    QPushButton *btn_108;
    QPushButton *btn_109;
    QPushButton *btn_110;
    QPushButton *btn_111;
    QPushButton *btn_112;
    QPushButton *btn_113;
    QPushButton *btn_114;
    QPushButton *btn_115;
    QPushButton *btn_116;
    QPushButton *btn_117;
    QPushButton *btn_118;
    QPushButton *btn_119;
    QPushButton *btn_120;
    QPushButton *btn_121;
    QPushButton *btn_122;
    QPushButton *btn_123;
    QPushButton *btn_124;
    QPushButton *btn_125;
    QPushButton *btn_126;
    QPushButton *btn_127;
    QPushButton *btn_128;
    QPushButton *btn_129;
    QPushButton *btn_130;
    QPushButton *btn_131;
    QPushButton *btn_132;
    QPushButton *btn_133;
    QPushButton *btn_134;
    QPushButton *btn_135;
    QPushButton *btn_136;
    QSpinBox *spinBox;
    QLabel *label;
    QPushButton *btnSolucionar;
    QPushButton *btnSiguiente;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1083, 614);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        frame = new QFrame(centralwidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(130, 90, 421, 411));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        btn_1 = new QPushButton(frame);
        btn_1->setObjectName(QString::fromUtf8("btn_1"));
        btn_1->setGeometry(QRect(10, 0, 50, 50));
        btn_2 = new QPushButton(frame);
        btn_2->setObjectName(QString::fromUtf8("btn_2"));
        btn_2->setGeometry(QRect(60, 0, 50, 50));
        btn_3 = new QPushButton(frame);
        btn_3->setObjectName(QString::fromUtf8("btn_3"));
        btn_3->setGeometry(QRect(110, 0, 50, 50));
        btn_4 = new QPushButton(frame);
        btn_4->setObjectName(QString::fromUtf8("btn_4"));
        btn_4->setGeometry(QRect(160, 0, 50, 50));
        btn_5 = new QPushButton(frame);
        btn_5->setObjectName(QString::fromUtf8("btn_5"));
        btn_5->setGeometry(QRect(220, 0, 50, 50));
        btn_6 = new QPushButton(frame);
        btn_6->setObjectName(QString::fromUtf8("btn_6"));
        btn_6->setGeometry(QRect(370, 0, 50, 50));
        btn_7 = new QPushButton(frame);
        btn_7->setObjectName(QString::fromUtf8("btn_7"));
        btn_7->setGeometry(QRect(270, 0, 50, 50));
        btn_8 = new QPushButton(frame);
        btn_8->setObjectName(QString::fromUtf8("btn_8"));
        btn_8->setGeometry(QRect(320, 0, 50, 50));
        btn_17 = new QPushButton(frame);
        btn_17->setObjectName(QString::fromUtf8("btn_17"));
        btn_17->setGeometry(QRect(320, 50, 50, 50));
        btn_18 = new QPushButton(frame);
        btn_18->setObjectName(QString::fromUtf8("btn_18"));
        btn_18->setGeometry(QRect(10, 50, 50, 50));
        btn_19 = new QPushButton(frame);
        btn_19->setObjectName(QString::fromUtf8("btn_19"));
        btn_19->setGeometry(QRect(220, 50, 50, 50));
        btn_20 = new QPushButton(frame);
        btn_20->setObjectName(QString::fromUtf8("btn_20"));
        btn_20->setGeometry(QRect(160, 50, 50, 50));
        btn_21 = new QPushButton(frame);
        btn_21->setObjectName(QString::fromUtf8("btn_21"));
        btn_21->setGeometry(QRect(370, 50, 50, 50));
        btn_22 = new QPushButton(frame);
        btn_22->setObjectName(QString::fromUtf8("btn_22"));
        btn_22->setGeometry(QRect(270, 50, 50, 50));
        btn_23 = new QPushButton(frame);
        btn_23->setObjectName(QString::fromUtf8("btn_23"));
        btn_23->setGeometry(QRect(60, 50, 50, 50));
        btn_24 = new QPushButton(frame);
        btn_24->setObjectName(QString::fromUtf8("btn_24"));
        btn_24->setGeometry(QRect(110, 50, 50, 50));
        btn_25 = new QPushButton(frame);
        btn_25->setObjectName(QString::fromUtf8("btn_25"));
        btn_25->setGeometry(QRect(320, 100, 50, 50));
        btn_26 = new QPushButton(frame);
        btn_26->setObjectName(QString::fromUtf8("btn_26"));
        btn_26->setGeometry(QRect(10, 100, 50, 50));
        btn_27 = new QPushButton(frame);
        btn_27->setObjectName(QString::fromUtf8("btn_27"));
        btn_27->setGeometry(QRect(220, 100, 50, 50));
        btn_28 = new QPushButton(frame);
        btn_28->setObjectName(QString::fromUtf8("btn_28"));
        btn_28->setGeometry(QRect(160, 100, 50, 50));
        btn_29 = new QPushButton(frame);
        btn_29->setObjectName(QString::fromUtf8("btn_29"));
        btn_29->setGeometry(QRect(370, 100, 50, 50));
        btn_30 = new QPushButton(frame);
        btn_30->setObjectName(QString::fromUtf8("btn_30"));
        btn_30->setGeometry(QRect(270, 100, 50, 50));
        btn_31 = new QPushButton(frame);
        btn_31->setObjectName(QString::fromUtf8("btn_31"));
        btn_31->setGeometry(QRect(60, 100, 50, 50));
        btn_32 = new QPushButton(frame);
        btn_32->setObjectName(QString::fromUtf8("btn_32"));
        btn_32->setGeometry(QRect(110, 100, 50, 50));
        btn_33 = new QPushButton(frame);
        btn_33->setObjectName(QString::fromUtf8("btn_33"));
        btn_33->setGeometry(QRect(320, 150, 50, 50));
        btn_34 = new QPushButton(frame);
        btn_34->setObjectName(QString::fromUtf8("btn_34"));
        btn_34->setGeometry(QRect(10, 150, 50, 50));
        btn_35 = new QPushButton(frame);
        btn_35->setObjectName(QString::fromUtf8("btn_35"));
        btn_35->setGeometry(QRect(220, 150, 50, 50));
        btn_36 = new QPushButton(frame);
        btn_36->setObjectName(QString::fromUtf8("btn_36"));
        btn_36->setGeometry(QRect(160, 150, 50, 50));
        btn_37 = new QPushButton(frame);
        btn_37->setObjectName(QString::fromUtf8("btn_37"));
        btn_37->setGeometry(QRect(370, 150, 50, 50));
        btn_38 = new QPushButton(frame);
        btn_38->setObjectName(QString::fromUtf8("btn_38"));
        btn_38->setGeometry(QRect(270, 150, 50, 50));
        btn_39 = new QPushButton(frame);
        btn_39->setObjectName(QString::fromUtf8("btn_39"));
        btn_39->setGeometry(QRect(60, 150, 50, 50));
        btn_40 = new QPushButton(frame);
        btn_40->setObjectName(QString::fromUtf8("btn_40"));
        btn_40->setGeometry(QRect(110, 150, 50, 50));
        btn_41 = new QPushButton(frame);
        btn_41->setObjectName(QString::fromUtf8("btn_41"));
        btn_41->setGeometry(QRect(320, 210, 50, 50));
        btn_42 = new QPushButton(frame);
        btn_42->setObjectName(QString::fromUtf8("btn_42"));
        btn_42->setGeometry(QRect(10, 210, 50, 50));
        btn_43 = new QPushButton(frame);
        btn_43->setObjectName(QString::fromUtf8("btn_43"));
        btn_43->setGeometry(QRect(220, 210, 50, 50));
        btn_44 = new QPushButton(frame);
        btn_44->setObjectName(QString::fromUtf8("btn_44"));
        btn_44->setGeometry(QRect(160, 210, 50, 50));
        btn_45 = new QPushButton(frame);
        btn_45->setObjectName(QString::fromUtf8("btn_45"));
        btn_45->setGeometry(QRect(370, 210, 50, 50));
        btn_46 = new QPushButton(frame);
        btn_46->setObjectName(QString::fromUtf8("btn_46"));
        btn_46->setGeometry(QRect(270, 210, 50, 50));
        btn_47 = new QPushButton(frame);
        btn_47->setObjectName(QString::fromUtf8("btn_47"));
        btn_47->setGeometry(QRect(60, 210, 50, 50));
        btn_48 = new QPushButton(frame);
        btn_48->setObjectName(QString::fromUtf8("btn_48"));
        btn_48->setGeometry(QRect(110, 210, 50, 50));
        btn_49 = new QPushButton(frame);
        btn_49->setObjectName(QString::fromUtf8("btn_49"));
        btn_49->setGeometry(QRect(320, 260, 50, 50));
        btn_50 = new QPushButton(frame);
        btn_50->setObjectName(QString::fromUtf8("btn_50"));
        btn_50->setGeometry(QRect(10, 260, 50, 50));
        btn_51 = new QPushButton(frame);
        btn_51->setObjectName(QString::fromUtf8("btn_51"));
        btn_51->setGeometry(QRect(220, 260, 50, 50));
        btn_52 = new QPushButton(frame);
        btn_52->setObjectName(QString::fromUtf8("btn_52"));
        btn_52->setGeometry(QRect(160, 260, 50, 50));
        btn_53 = new QPushButton(frame);
        btn_53->setObjectName(QString::fromUtf8("btn_53"));
        btn_53->setGeometry(QRect(370, 260, 50, 50));
        btn_54 = new QPushButton(frame);
        btn_54->setObjectName(QString::fromUtf8("btn_54"));
        btn_54->setGeometry(QRect(270, 260, 50, 50));
        btn_55 = new QPushButton(frame);
        btn_55->setObjectName(QString::fromUtf8("btn_55"));
        btn_55->setGeometry(QRect(60, 260, 50, 50));
        btn_56 = new QPushButton(frame);
        btn_56->setObjectName(QString::fromUtf8("btn_56"));
        btn_56->setGeometry(QRect(110, 260, 50, 50));
        btn_57 = new QPushButton(frame);
        btn_57->setObjectName(QString::fromUtf8("btn_57"));
        btn_57->setGeometry(QRect(320, 310, 50, 50));
        btn_58 = new QPushButton(frame);
        btn_58->setObjectName(QString::fromUtf8("btn_58"));
        btn_58->setGeometry(QRect(10, 310, 50, 50));
        btn_59 = new QPushButton(frame);
        btn_59->setObjectName(QString::fromUtf8("btn_59"));
        btn_59->setGeometry(QRect(220, 310, 50, 50));
        btn_60 = new QPushButton(frame);
        btn_60->setObjectName(QString::fromUtf8("btn_60"));
        btn_60->setGeometry(QRect(160, 310, 50, 50));
        btn_61 = new QPushButton(frame);
        btn_61->setObjectName(QString::fromUtf8("btn_61"));
        btn_61->setGeometry(QRect(370, 310, 50, 50));
        btn_62 = new QPushButton(frame);
        btn_62->setObjectName(QString::fromUtf8("btn_62"));
        btn_62->setGeometry(QRect(270, 310, 50, 50));
        btn_63 = new QPushButton(frame);
        btn_63->setObjectName(QString::fromUtf8("btn_63"));
        btn_63->setGeometry(QRect(60, 310, 50, 50));
        btn_64 = new QPushButton(frame);
        btn_64->setObjectName(QString::fromUtf8("btn_64"));
        btn_64->setGeometry(QRect(110, 310, 50, 50));
        btn_65 = new QPushButton(frame);
        btn_65->setObjectName(QString::fromUtf8("btn_65"));
        btn_65->setGeometry(QRect(320, 360, 50, 50));
        btn_66 = new QPushButton(frame);
        btn_66->setObjectName(QString::fromUtf8("btn_66"));
        btn_66->setGeometry(QRect(10, 360, 50, 50));
        btn_67 = new QPushButton(frame);
        btn_67->setObjectName(QString::fromUtf8("btn_67"));
        btn_67->setGeometry(QRect(220, 360, 50, 50));
        btn_68 = new QPushButton(frame);
        btn_68->setObjectName(QString::fromUtf8("btn_68"));
        btn_68->setGeometry(QRect(160, 360, 50, 50));
        btn_69 = new QPushButton(frame);
        btn_69->setObjectName(QString::fromUtf8("btn_69"));
        btn_69->setGeometry(QRect(370, 360, 50, 50));
        btn_70 = new QPushButton(frame);
        btn_70->setObjectName(QString::fromUtf8("btn_70"));
        btn_70->setGeometry(QRect(270, 360, 50, 50));
        btn_71 = new QPushButton(frame);
        btn_71->setObjectName(QString::fromUtf8("btn_71"));
        btn_71->setGeometry(QRect(60, 360, 50, 50));
        btn_72 = new QPushButton(frame);
        btn_72->setObjectName(QString::fromUtf8("btn_72"));
        btn_72->setGeometry(QRect(110, 360, 50, 50));
        frame_2 = new QFrame(centralwidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(619, 90, 411, 411));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        btn_73 = new QPushButton(frame_2);
        btn_73->setObjectName(QString::fromUtf8("btn_73"));
        btn_73->setGeometry(QRect(0, 0, 50, 50));
        btn_74 = new QPushButton(frame_2);
        btn_74->setObjectName(QString::fromUtf8("btn_74"));
        btn_74->setGeometry(QRect(50, 0, 50, 50));
        btn_75 = new QPushButton(frame_2);
        btn_75->setObjectName(QString::fromUtf8("btn_75"));
        btn_75->setGeometry(QRect(100, 0, 50, 50));
        btn_76 = new QPushButton(frame_2);
        btn_76->setObjectName(QString::fromUtf8("btn_76"));
        btn_76->setGeometry(QRect(150, 0, 50, 50));
        btn_77 = new QPushButton(frame_2);
        btn_77->setObjectName(QString::fromUtf8("btn_77"));
        btn_77->setGeometry(QRect(210, 0, 50, 50));
        btn_78 = new QPushButton(frame_2);
        btn_78->setObjectName(QString::fromUtf8("btn_78"));
        btn_78->setGeometry(QRect(360, 0, 50, 50));
        btn_79 = new QPushButton(frame_2);
        btn_79->setObjectName(QString::fromUtf8("btn_79"));
        btn_79->setGeometry(QRect(260, 0, 50, 50));
        btn_80 = new QPushButton(frame_2);
        btn_80->setObjectName(QString::fromUtf8("btn_80"));
        btn_80->setGeometry(QRect(310, 0, 50, 50));
        btn_81 = new QPushButton(frame_2);
        btn_81->setObjectName(QString::fromUtf8("btn_81"));
        btn_81->setGeometry(QRect(310, 50, 50, 50));
        btn_82 = new QPushButton(frame_2);
        btn_82->setObjectName(QString::fromUtf8("btn_82"));
        btn_82->setGeometry(QRect(0, 50, 50, 50));
        btn_83 = new QPushButton(frame_2);
        btn_83->setObjectName(QString::fromUtf8("btn_83"));
        btn_83->setGeometry(QRect(210, 50, 50, 50));
        btn_84 = new QPushButton(frame_2);
        btn_84->setObjectName(QString::fromUtf8("btn_84"));
        btn_84->setGeometry(QRect(150, 50, 50, 50));
        btn_85 = new QPushButton(frame_2);
        btn_85->setObjectName(QString::fromUtf8("btn_85"));
        btn_85->setGeometry(QRect(360, 50, 50, 50));
        btn_86 = new QPushButton(frame_2);
        btn_86->setObjectName(QString::fromUtf8("btn_86"));
        btn_86->setGeometry(QRect(260, 50, 50, 50));
        btn_87 = new QPushButton(frame_2);
        btn_87->setObjectName(QString::fromUtf8("btn_87"));
        btn_87->setGeometry(QRect(50, 50, 50, 50));
        btn_88 = new QPushButton(frame_2);
        btn_88->setObjectName(QString::fromUtf8("btn_88"));
        btn_88->setGeometry(QRect(100, 50, 50, 50));
        btn_89 = new QPushButton(frame_2);
        btn_89->setObjectName(QString::fromUtf8("btn_89"));
        btn_89->setGeometry(QRect(310, 100, 50, 50));
        btn_90 = new QPushButton(frame_2);
        btn_90->setObjectName(QString::fromUtf8("btn_90"));
        btn_90->setGeometry(QRect(0, 100, 50, 50));
        btn_91 = new QPushButton(frame_2);
        btn_91->setObjectName(QString::fromUtf8("btn_91"));
        btn_91->setGeometry(QRect(210, 100, 50, 50));
        btn_92 = new QPushButton(frame_2);
        btn_92->setObjectName(QString::fromUtf8("btn_92"));
        btn_92->setGeometry(QRect(150, 100, 50, 50));
        btn_93 = new QPushButton(frame_2);
        btn_93->setObjectName(QString::fromUtf8("btn_93"));
        btn_93->setGeometry(QRect(360, 100, 50, 50));
        btn_94 = new QPushButton(frame_2);
        btn_94->setObjectName(QString::fromUtf8("btn_94"));
        btn_94->setGeometry(QRect(260, 100, 50, 50));
        btn_95 = new QPushButton(frame_2);
        btn_95->setObjectName(QString::fromUtf8("btn_95"));
        btn_95->setGeometry(QRect(50, 100, 50, 50));
        btn_96 = new QPushButton(frame_2);
        btn_96->setObjectName(QString::fromUtf8("btn_96"));
        btn_96->setGeometry(QRect(100, 100, 50, 50));
        btn_97 = new QPushButton(frame_2);
        btn_97->setObjectName(QString::fromUtf8("btn_97"));
        btn_97->setGeometry(QRect(310, 150, 50, 50));
        btn_98 = new QPushButton(frame_2);
        btn_98->setObjectName(QString::fromUtf8("btn_98"));
        btn_98->setGeometry(QRect(0, 150, 50, 50));
        btn_99 = new QPushButton(frame_2);
        btn_99->setObjectName(QString::fromUtf8("btn_99"));
        btn_99->setGeometry(QRect(210, 150, 50, 50));
        btn_100 = new QPushButton(frame_2);
        btn_100->setObjectName(QString::fromUtf8("btn_100"));
        btn_100->setGeometry(QRect(150, 150, 50, 50));
        btn_101 = new QPushButton(frame_2);
        btn_101->setObjectName(QString::fromUtf8("btn_101"));
        btn_101->setGeometry(QRect(360, 150, 50, 50));
        btn_102 = new QPushButton(frame_2);
        btn_102->setObjectName(QString::fromUtf8("btn_102"));
        btn_102->setGeometry(QRect(260, 150, 50, 50));
        btn_103 = new QPushButton(frame_2);
        btn_103->setObjectName(QString::fromUtf8("btn_103"));
        btn_103->setGeometry(QRect(50, 150, 50, 50));
        btn_104 = new QPushButton(frame_2);
        btn_104->setObjectName(QString::fromUtf8("btn_104"));
        btn_104->setGeometry(QRect(100, 150, 50, 50));
        btn_105 = new QPushButton(frame_2);
        btn_105->setObjectName(QString::fromUtf8("btn_105"));
        btn_105->setGeometry(QRect(310, 210, 50, 50));
        btn_106 = new QPushButton(frame_2);
        btn_106->setObjectName(QString::fromUtf8("btn_106"));
        btn_106->setGeometry(QRect(0, 210, 50, 50));
        btn_107 = new QPushButton(frame_2);
        btn_107->setObjectName(QString::fromUtf8("btn_107"));
        btn_107->setGeometry(QRect(210, 210, 50, 50));
        btn_108 = new QPushButton(frame_2);
        btn_108->setObjectName(QString::fromUtf8("btn_108"));
        btn_108->setGeometry(QRect(150, 210, 50, 50));
        btn_109 = new QPushButton(frame_2);
        btn_109->setObjectName(QString::fromUtf8("btn_109"));
        btn_109->setGeometry(QRect(360, 210, 50, 50));
        btn_110 = new QPushButton(frame_2);
        btn_110->setObjectName(QString::fromUtf8("btn_110"));
        btn_110->setGeometry(QRect(260, 210, 50, 50));
        btn_111 = new QPushButton(frame_2);
        btn_111->setObjectName(QString::fromUtf8("btn_111"));
        btn_111->setGeometry(QRect(50, 210, 50, 50));
        btn_112 = new QPushButton(frame_2);
        btn_112->setObjectName(QString::fromUtf8("btn_112"));
        btn_112->setGeometry(QRect(100, 210, 50, 50));
        btn_113 = new QPushButton(frame_2);
        btn_113->setObjectName(QString::fromUtf8("btn_113"));
        btn_113->setGeometry(QRect(310, 260, 50, 50));
        btn_114 = new QPushButton(frame_2);
        btn_114->setObjectName(QString::fromUtf8("btn_114"));
        btn_114->setGeometry(QRect(0, 260, 50, 50));
        btn_115 = new QPushButton(frame_2);
        btn_115->setObjectName(QString::fromUtf8("btn_115"));
        btn_115->setGeometry(QRect(210, 260, 50, 50));
        btn_116 = new QPushButton(frame_2);
        btn_116->setObjectName(QString::fromUtf8("btn_116"));
        btn_116->setGeometry(QRect(150, 260, 50, 50));
        btn_117 = new QPushButton(frame_2);
        btn_117->setObjectName(QString::fromUtf8("btn_117"));
        btn_117->setGeometry(QRect(360, 260, 50, 50));
        btn_118 = new QPushButton(frame_2);
        btn_118->setObjectName(QString::fromUtf8("btn_118"));
        btn_118->setGeometry(QRect(260, 260, 50, 50));
        btn_119 = new QPushButton(frame_2);
        btn_119->setObjectName(QString::fromUtf8("btn_119"));
        btn_119->setGeometry(QRect(50, 260, 50, 50));
        btn_120 = new QPushButton(frame_2);
        btn_120->setObjectName(QString::fromUtf8("btn_120"));
        btn_120->setGeometry(QRect(100, 260, 50, 50));
        btn_121 = new QPushButton(frame_2);
        btn_121->setObjectName(QString::fromUtf8("btn_121"));
        btn_121->setGeometry(QRect(310, 310, 50, 50));
        btn_122 = new QPushButton(frame_2);
        btn_122->setObjectName(QString::fromUtf8("btn_122"));
        btn_122->setGeometry(QRect(0, 310, 50, 50));
        btn_123 = new QPushButton(frame_2);
        btn_123->setObjectName(QString::fromUtf8("btn_123"));
        btn_123->setGeometry(QRect(210, 310, 50, 50));
        btn_124 = new QPushButton(frame_2);
        btn_124->setObjectName(QString::fromUtf8("btn_124"));
        btn_124->setGeometry(QRect(150, 310, 50, 50));
        btn_125 = new QPushButton(frame_2);
        btn_125->setObjectName(QString::fromUtf8("btn_125"));
        btn_125->setGeometry(QRect(360, 310, 50, 50));
        btn_126 = new QPushButton(frame_2);
        btn_126->setObjectName(QString::fromUtf8("btn_126"));
        btn_126->setGeometry(QRect(260, 310, 50, 50));
        btn_127 = new QPushButton(frame_2);
        btn_127->setObjectName(QString::fromUtf8("btn_127"));
        btn_127->setGeometry(QRect(50, 310, 50, 50));
        btn_128 = new QPushButton(frame_2);
        btn_128->setObjectName(QString::fromUtf8("btn_128"));
        btn_128->setGeometry(QRect(100, 310, 50, 50));
        btn_129 = new QPushButton(frame_2);
        btn_129->setObjectName(QString::fromUtf8("btn_129"));
        btn_129->setGeometry(QRect(310, 360, 50, 50));
        btn_130 = new QPushButton(frame_2);
        btn_130->setObjectName(QString::fromUtf8("btn_130"));
        btn_130->setGeometry(QRect(0, 360, 50, 50));
        btn_131 = new QPushButton(frame_2);
        btn_131->setObjectName(QString::fromUtf8("btn_131"));
        btn_131->setGeometry(QRect(210, 360, 50, 50));
        btn_132 = new QPushButton(frame_2);
        btn_132->setObjectName(QString::fromUtf8("btn_132"));
        btn_132->setGeometry(QRect(150, 360, 50, 50));
        btn_133 = new QPushButton(frame_2);
        btn_133->setObjectName(QString::fromUtf8("btn_133"));
        btn_133->setGeometry(QRect(360, 360, 50, 50));
        btn_134 = new QPushButton(frame_2);
        btn_134->setObjectName(QString::fromUtf8("btn_134"));
        btn_134->setGeometry(QRect(260, 360, 50, 50));
        btn_135 = new QPushButton(frame_2);
        btn_135->setObjectName(QString::fromUtf8("btn_135"));
        btn_135->setGeometry(QRect(50, 360, 50, 50));
        btn_136 = new QPushButton(frame_2);
        btn_136->setObjectName(QString::fromUtf8("btn_136"));
        btn_136->setGeometry(QRect(100, 360, 50, 50));
        spinBox = new QSpinBox(centralwidget);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(40, 180, 46, 25));
        spinBox->setMinimum(1);
        spinBox->setMaximum(16);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 150, 91, 16));
        btnSolucionar = new QPushButton(centralwidget);
        btnSolucionar->setObjectName(QString::fromUtf8("btnSolucionar"));
        btnSolucionar->setGeometry(QRect(300, 520, 80, 25));
        btnSiguiente = new QPushButton(centralwidget);
        btnSiguiente->setObjectName(QString::fromUtf8("btnSiguiente"));
        btnSiguiente->setGeometry(QRect(790, 520, 80, 25));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(310, 60, 71, 16));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(800, 60, 71, 16));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(550, 20, 81, 16));
        QFont font;
        font.setPointSize(12);
        label_4->setFont(font);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1083, 25));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        btn_1->setText(QString());
        btn_2->setText(QString());
        btn_3->setText(QString());
        btn_4->setText(QString());
        btn_5->setText(QString());
        btn_6->setText(QString());
        btn_7->setText(QString());
        btn_8->setText(QString());
        btn_17->setText(QString());
        btn_18->setText(QString());
        btn_19->setText(QString());
        btn_20->setText(QString());
        btn_21->setText(QString());
        btn_22->setText(QString());
        btn_23->setText(QString());
        btn_24->setText(QString());
        btn_25->setText(QString());
        btn_26->setText(QString());
        btn_27->setText(QString());
        btn_28->setText(QString());
        btn_29->setText(QString());
        btn_30->setText(QString());
        btn_31->setText(QString());
        btn_32->setText(QString());
        btn_33->setText(QString());
        btn_34->setText(QString());
        btn_35->setText(QString());
        btn_36->setText(QString());
        btn_37->setText(QString());
        btn_38->setText(QString());
        btn_39->setText(QString());
        btn_40->setText(QString());
        btn_41->setText(QString());
        btn_42->setText(QString());
        btn_43->setText(QString());
        btn_44->setText(QString());
        btn_45->setText(QString());
        btn_46->setText(QString());
        btn_47->setText(QString());
        btn_48->setText(QString());
        btn_49->setText(QString());
        btn_50->setText(QString());
        btn_51->setText(QString());
        btn_52->setText(QString());
        btn_53->setText(QString());
        btn_54->setText(QString());
        btn_55->setText(QString());
        btn_56->setText(QString());
        btn_57->setText(QString());
        btn_58->setText(QString());
        btn_59->setText(QString());
        btn_60->setText(QString());
        btn_61->setText(QString());
        btn_62->setText(QString());
        btn_63->setText(QString());
        btn_64->setText(QString());
        btn_65->setText(QString());
        btn_66->setText(QString());
        btn_67->setText(QString());
        btn_68->setText(QString());
        btn_69->setText(QString());
        btn_70->setText(QString());
        btn_71->setText(QString());
        btn_72->setText(QString());
        btn_73->setText(QString());
        btn_74->setText(QString());
        btn_75->setText(QString());
        btn_76->setText(QString());
        btn_77->setText(QString());
        btn_78->setText(QString());
        btn_79->setText(QString());
        btn_80->setText(QString());
        btn_81->setText(QString());
        btn_82->setText(QString());
        btn_83->setText(QString());
        btn_84->setText(QString());
        btn_85->setText(QString());
        btn_86->setText(QString());
        btn_87->setText(QString());
        btn_88->setText(QString());
        btn_89->setText(QString());
        btn_90->setText(QString());
        btn_91->setText(QString());
        btn_92->setText(QString());
        btn_93->setText(QString());
        btn_94->setText(QString());
        btn_95->setText(QString());
        btn_96->setText(QString());
        btn_97->setText(QString());
        btn_98->setText(QString());
        btn_99->setText(QString());
        btn_100->setText(QString());
        btn_101->setText(QString());
        btn_102->setText(QString());
        btn_103->setText(QString());
        btn_104->setText(QString());
        btn_105->setText(QString());
        btn_106->setText(QString());
        btn_107->setText(QString());
        btn_108->setText(QString());
        btn_109->setText(QString());
        btn_110->setText(QString());
        btn_111->setText(QString());
        btn_112->setText(QString());
        btn_113->setText(QString());
        btn_114->setText(QString());
        btn_115->setText(QString());
        btn_116->setText(QString());
        btn_117->setText(QString());
        btn_118->setText(QString());
        btn_119->setText(QString());
        btn_120->setText(QString());
        btn_121->setText(QString());
        btn_122->setText(QString());
        btn_123->setText(QString());
        btn_124->setText(QString());
        btn_125->setText(QString());
        btn_126->setText(QString());
        btn_127->setText(QString());
        btn_128->setText(QString());
        btn_129->setText(QString());
        btn_130->setText(QString());
        btn_131->setText(QString());
        btn_132->setText(QString());
        btn_133->setText(QString());
        btn_134->setText(QString());
        btn_135->setText(QString());
        btn_136->setText(QString());
        label->setText(QCoreApplication::translate("MainWindow", "Elegir numero:", nullptr));
        btnSolucionar->setText(QCoreApplication::translate("MainWindow", "Solucionar", nullptr));
        btnSiguiente->setText(QCoreApplication::translate("MainWindow", "Siguiente", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Automatico", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Por Pasos", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Sudoku", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
