/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QComboBox *comboBox;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QComboBox *comboBox_2;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QComboBox *comboBox_3;
    QComboBox *comboBox_4;
    QComboBox *comboBox_5;
    QLabel *label_36;
    QLabel *label_37;
    QComboBox *comboBox_6;
    QComboBox *comboBox_7;
    QComboBox *comboBox_8;
    QLabel *label_38;
    QLabel *label_39;
    QComboBox *comboBox_9;
    QComboBox *comboBox_10;
    QLabel *label_40;
    QComboBox *comboBox_11;
    QComboBox *comboBox_12;
    QLabel *label_41;
    QComboBox *comboBox_13;
    QLabel *label_42;
    QComboBox *comboBox_14;
    QComboBox *comboBox_15;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QComboBox *comboBox_16;
    QLabel *label_46;
    QLabel *label_47;
    QComboBox *comboBox_17;
    QComboBox *comboBox_18;
    QLabel *label_48;
    QComboBox *comboBox_19;
    QComboBox *comboBox_20;
    QLabel *label_49;
    QComboBox *comboBox_21;
    QLabel *label_50;
    QComboBox *comboBox_22;
    QComboBox *comboBox_23;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QComboBox *comboBox_24;
    QLabel *label_54;
    QLabel *label_55;
    QComboBox *comboBox_25;
    QComboBox *comboBox_26;
    QLabel *label_56;
    QComboBox *comboBox_27;
    QComboBox *comboBox_28;
    QLabel *label_57;
    QComboBox *comboBox_30;
    QComboBox *comboBox_31;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *label_86;
    QPushButton *pushButton;
    QLabel *label_87;
    QLineEdit *lineEdit_3;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLabel *label_103;
    QLabel *label_104;
    QLabel *label_105;
    QLabel *label_106;
    QLabel *label_107;
    QLabel *label_108;
    QLabel *label_109;
    QLabel *label_110;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1704, 897);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 0, 861, 871));
        label->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa Rica.png")));
        comboBox = new QComboBox(centralwidget);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(1270, 320, 121, 22));
        QFont font;
        font.setPointSize(9);
        comboBox->setFont(font);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(890, 20, 91, 21));
        QFont font1;
        font1.setPointSize(14);
        label_2->setFont(font1);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(140, 310, 141, 101));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0054_Forma-1.png")));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(140, 210, 41, 111));
        label_4->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0053_Forma-2.png")));
        comboBox_2 = new QComboBox(centralwidget);
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->addItem(QString());
        comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));
        comboBox_2->setGeometry(QRect(1270, 410, 121, 22));
        comboBox_2->setFont(font);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(170, 170, 51, 51));
        label_5->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0052_Forma-3.png")));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(160, 120, 61, 61));
        label_6->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0051_Forma-4.png")));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(true);
        label_7->setGeometry(QRect(170, 210, 61, 51));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0050_Forma-5.png")));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setEnabled(true);
        label_8->setGeometry(QRect(230, 190, 71, 71));
        label_8->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0049_Forma-6.png")));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setEnabled(true);
        label_9->setGeometry(QRect(290, 150, 81, 51));
        label_9->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0048_Forma-7.png")));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setEnabled(true);
        label_10->setGeometry(QRect(370, 150, 81, 51));
        label_10->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0047_Forma-8.png")));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setEnabled(true);
        label_11->setGeometry(QRect(370, 150, 21, 91));
        label_11->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0046_Forma-9.png")));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setEnabled(true);
        label_12->setGeometry(QRect(310, 230, 71, 51));
        label_12->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0045_Forma-10.png")));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(true);
        label_13->setGeometry(QRect(310, 270, 61, 71));
        label_13->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0044_Forma-11.png")));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setEnabled(true);
        label_14->setGeometry(QRect(370, 300, 71, 41));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0043_Forma-12.png")));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(true);
        label_15->setGeometry(QRect(200, 300, 61, 101));
        label_15->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0036_Forma-19.png")));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(200, 270, 81, 51));
        label_16->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0037_Forma-18.png")));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(true);
        label_17->setGeometry(QRect(280, 290, 91, 51));
        label_17->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0038_Forma-17.png")));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setEnabled(true);
        label_18->setGeometry(QRect(230, 250, 91, 41));
        label_18->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0003_Forma-52.png")));
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(220, 170, 71, 21));
        label_19->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0002_Forma-53.png")));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setEnabled(true);
        label_20->setGeometry(QRect(380, 230, 41, 41));
        label_20->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0007_Forma-48.png")));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setEnabled(true);
        label_21->setGeometry(QRect(420, 190, 41, 81));
        label_21->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0006_Forma-49.png")));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setEnabled(true);
        label_22->setGeometry(QRect(430, 230, 41, 91));
        label_22->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0042_Forma-13.png")));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setEnabled(true);
        label_23->setGeometry(QRect(450, 190, 21, 61));
        label_23->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0005_Forma-50.png")));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setEnabled(true);
        label_24->setGeometry(QRect(460, 230, 111, 101));
        label_24->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0041_Forma-14.png")));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setEnabled(true);
        label_25->setGeometry(QRect(460, 220, 131, 31));
        label_25->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0021_Forma-34.png")));
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setEnabled(true);
        label_26->setGeometry(QRect(560, 230, 41, 91));
        label_26->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0022_Forma-33.png")));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setEnabled(true);
        label_27->setGeometry(QRect(370, 340, 81, 101));
        label_27->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0035_Forma-20.png")));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setEnabled(true);
        label_28->setGeometry(QRect(440, 370, 20, 71));
        label_28->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0009_Forma-46.png")));
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setEnabled(true);
        label_29->setGeometry(QRect(460, 330, 31, 51));
        label_29->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0008_Forma-47.png")));
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setEnabled(true);
        label_30->setGeometry(QRect(460, 240, 41, 101));
        label_30->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0039_Forma-16.png")));
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setEnabled(true);
        label_31->setGeometry(QRect(490, 330, 31, 61));
        label_31->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0004_Forma-51.png")));
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setEnabled(true);
        label_32->setGeometry(QRect(520, 320, 61, 71));
        label_32->setPixmap(QPixmap(QString::fromUtf8("../../Imagenes/Costa-Rica_0040_Forma-15.png")));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(890, 50, 81, 21));
        label_33->setFont(font1);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(890, 80, 91, 21));
        label_34->setFont(font1);
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(890, 110, 91, 21));
        label_35->setFont(font1);
        comboBox_3 = new QComboBox(centralwidget);
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->setObjectName(QString::fromUtf8("comboBox_3"));
        comboBox_3->setGeometry(QRect(1000, 20, 121, 22));
        comboBox_3->setFont(font);
        comboBox_4 = new QComboBox(centralwidget);
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->addItem(QString());
        comboBox_4->setObjectName(QString::fromUtf8("comboBox_4"));
        comboBox_4->setGeometry(QRect(1000, 50, 121, 22));
        comboBox_4->setFont(font);
        comboBox_5 = new QComboBox(centralwidget);
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->addItem(QString());
        comboBox_5->setObjectName(QString::fromUtf8("comboBox_5"));
        comboBox_5->setGeometry(QRect(1000, 80, 121, 22));
        comboBox_5->setFont(font);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(890, 170, 91, 21));
        label_36->setFont(font1);
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(890, 230, 91, 21));
        label_37->setFont(font1);
        comboBox_6 = new QComboBox(centralwidget);
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->setObjectName(QString::fromUtf8("comboBox_6"));
        comboBox_6->setGeometry(QRect(1000, 110, 121, 22));
        comboBox_6->setFont(font);
        comboBox_7 = new QComboBox(centralwidget);
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->setObjectName(QString::fromUtf8("comboBox_7"));
        comboBox_7->setGeometry(QRect(1000, 140, 121, 22));
        comboBox_7->setFont(font);
        comboBox_8 = new QComboBox(centralwidget);
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->setObjectName(QString::fromUtf8("comboBox_8"));
        comboBox_8->setGeometry(QRect(1000, 170, 121, 22));
        comboBox_8->setFont(font);
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(890, 140, 91, 21));
        label_38->setFont(font1);
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(890, 200, 91, 21));
        label_39->setFont(font1);
        comboBox_9 = new QComboBox(centralwidget);
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->addItem(QString());
        comboBox_9->setObjectName(QString::fromUtf8("comboBox_9"));
        comboBox_9->setGeometry(QRect(1000, 200, 121, 22));
        comboBox_9->setFont(font);
        comboBox_10 = new QComboBox(centralwidget);
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->addItem(QString());
        comboBox_10->setObjectName(QString::fromUtf8("comboBox_10"));
        comboBox_10->setGeometry(QRect(1000, 230, 121, 22));
        comboBox_10->setFont(font);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(890, 290, 91, 21));
        label_40->setFont(font1);
        comboBox_11 = new QComboBox(centralwidget);
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->addItem(QString());
        comboBox_11->setObjectName(QString::fromUtf8("comboBox_11"));
        comboBox_11->setGeometry(QRect(1000, 260, 121, 22));
        comboBox_11->setFont(font);
        comboBox_12 = new QComboBox(centralwidget);
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->addItem(QString());
        comboBox_12->setObjectName(QString::fromUtf8("comboBox_12"));
        comboBox_12->setGeometry(QRect(1000, 290, 121, 22));
        comboBox_12->setFont(font);
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(890, 350, 101, 21));
        label_41->setFont(font1);
        comboBox_13 = new QComboBox(centralwidget);
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->addItem(QString());
        comboBox_13->setObjectName(QString::fromUtf8("comboBox_13"));
        comboBox_13->setGeometry(QRect(1000, 320, 121, 22));
        comboBox_13->setFont(font);
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(890, 440, 91, 21));
        label_42->setFont(font1);
        comboBox_14 = new QComboBox(centralwidget);
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->addItem(QString());
        comboBox_14->setObjectName(QString::fromUtf8("comboBox_14"));
        comboBox_14->setGeometry(QRect(1000, 350, 121, 22));
        comboBox_14->setFont(font);
        comboBox_15 = new QComboBox(centralwidget);
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->addItem(QString());
        comboBox_15->setObjectName(QString::fromUtf8("comboBox_15"));
        comboBox_15->setGeometry(QRect(1000, 380, 121, 22));
        comboBox_15->setFont(font);
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(890, 470, 91, 21));
        label_43->setFont(font1);
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(890, 410, 101, 21));
        label_44->setFont(font1);
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(890, 260, 91, 21));
        label_45->setFont(font1);
        comboBox_16 = new QComboBox(centralwidget);
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->addItem(QString());
        comboBox_16->setObjectName(QString::fromUtf8("comboBox_16"));
        comboBox_16->setGeometry(QRect(1000, 410, 121, 22));
        comboBox_16->setFont(font);
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(890, 320, 91, 21));
        label_46->setFont(font1);
        label_47 = new QLabel(centralwidget);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(890, 380, 91, 21));
        label_47->setFont(font1);
        comboBox_17 = new QComboBox(centralwidget);
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->addItem(QString());
        comboBox_17->setObjectName(QString::fromUtf8("comboBox_17"));
        comboBox_17->setGeometry(QRect(1000, 440, 121, 22));
        comboBox_17->setFont(font);
        comboBox_18 = new QComboBox(centralwidget);
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->addItem(QString());
        comboBox_18->setObjectName(QString::fromUtf8("comboBox_18"));
        comboBox_18->setGeometry(QRect(1000, 470, 121, 22));
        comboBox_18->setFont(font);
        label_48 = new QLabel(centralwidget);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(1150, 50, 91, 21));
        label_48->setFont(font1);
        comboBox_19 = new QComboBox(centralwidget);
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->addItem(QString());
        comboBox_19->setObjectName(QString::fromUtf8("comboBox_19"));
        comboBox_19->setGeometry(QRect(1270, 20, 121, 22));
        comboBox_19->setFont(font);
        comboBox_20 = new QComboBox(centralwidget);
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->addItem(QString());
        comboBox_20->setObjectName(QString::fromUtf8("comboBox_20"));
        comboBox_20->setGeometry(QRect(1270, 50, 121, 22));
        comboBox_20->setFont(font);
        label_49 = new QLabel(centralwidget);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(1150, 110, 91, 21));
        label_49->setFont(font1);
        comboBox_21 = new QComboBox(centralwidget);
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->addItem(QString());
        comboBox_21->setObjectName(QString::fromUtf8("comboBox_21"));
        comboBox_21->setGeometry(QRect(1270, 80, 121, 22));
        comboBox_21->setFont(font);
        label_50 = new QLabel(centralwidget);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(1150, 200, 91, 21));
        label_50->setFont(font1);
        comboBox_22 = new QComboBox(centralwidget);
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->addItem(QString());
        comboBox_22->setObjectName(QString::fromUtf8("comboBox_22"));
        comboBox_22->setGeometry(QRect(1270, 110, 121, 22));
        comboBox_22->setFont(font);
        comboBox_23 = new QComboBox(centralwidget);
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->addItem(QString());
        comboBox_23->setObjectName(QString::fromUtf8("comboBox_23"));
        comboBox_23->setGeometry(QRect(1270, 140, 121, 22));
        comboBox_23->setFont(font);
        label_51 = new QLabel(centralwidget);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(1150, 230, 91, 21));
        label_51->setFont(font1);
        label_52 = new QLabel(centralwidget);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(1150, 170, 91, 21));
        label_52->setFont(font1);
        label_53 = new QLabel(centralwidget);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(1150, 20, 91, 21));
        label_53->setFont(font1);
        comboBox_24 = new QComboBox(centralwidget);
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->addItem(QString());
        comboBox_24->setObjectName(QString::fromUtf8("comboBox_24"));
        comboBox_24->setGeometry(QRect(1270, 170, 121, 22));
        comboBox_24->setFont(font);
        label_54 = new QLabel(centralwidget);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(1150, 80, 91, 21));
        label_54->setFont(font1);
        label_55 = new QLabel(centralwidget);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(1150, 140, 91, 21));
        label_55->setFont(font1);
        comboBox_25 = new QComboBox(centralwidget);
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->addItem(QString());
        comboBox_25->setObjectName(QString::fromUtf8("comboBox_25"));
        comboBox_25->setGeometry(QRect(1270, 200, 121, 22));
        comboBox_25->setFont(font);
        comboBox_26 = new QComboBox(centralwidget);
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->addItem(QString());
        comboBox_26->setObjectName(QString::fromUtf8("comboBox_26"));
        comboBox_26->setGeometry(QRect(1270, 230, 121, 22));
        comboBox_26->setFont(font);
        label_56 = new QLabel(centralwidget);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(1150, 290, 101, 21));
        label_56->setFont(font1);
        comboBox_27 = new QComboBox(centralwidget);
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->addItem(QString());
        comboBox_27->setObjectName(QString::fromUtf8("comboBox_27"));
        comboBox_27->setGeometry(QRect(1270, 260, 121, 22));
        comboBox_27->setFont(font);
        comboBox_28 = new QComboBox(centralwidget);
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->addItem(QString());
        comboBox_28->setObjectName(QString::fromUtf8("comboBox_28"));
        comboBox_28->setGeometry(QRect(1270, 290, 121, 22));
        comboBox_28->setFont(font);
        label_57 = new QLabel(centralwidget);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(1150, 350, 91, 21));
        label_57->setFont(font1);
        comboBox_30 = new QComboBox(centralwidget);
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->addItem(QString());
        comboBox_30->setObjectName(QString::fromUtf8("comboBox_30"));
        comboBox_30->setGeometry(QRect(1270, 350, 121, 22));
        comboBox_30->setFont(font);
        comboBox_31 = new QComboBox(centralwidget);
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->addItem(QString());
        comboBox_31->setObjectName(QString::fromUtf8("comboBox_31"));
        comboBox_31->setGeometry(QRect(1270, 380, 121, 22));
        comboBox_31->setFont(font);
        label_60 = new QLabel(centralwidget);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(1150, 410, 91, 21));
        label_60->setFont(font1);
        label_61 = new QLabel(centralwidget);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(1150, 260, 101, 21));
        label_61->setFont(font1);
        label_62 = new QLabel(centralwidget);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(1150, 320, 91, 21));
        label_62->setFont(font1);
        label_63 = new QLabel(centralwidget);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(1150, 380, 91, 21));
        label_63->setFont(font1);
        lineEdit = new QLineEdit(centralwidget);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(990, 550, 113, 20));
        lineEdit_2 = new QLineEdit(centralwidget);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(990, 590, 113, 20));
        label_58 = new QLabel(centralwidget);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(890, 550, 91, 21));
        QFont font2;
        font2.setPointSize(11);
        label_58->setFont(font2);
        label_59 = new QLabel(centralwidget);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(890, 590, 81, 21));
        label_59->setFont(font2);
        label_64 = new QLabel(centralwidget);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(250, 390, 16, 21));
        label_64->setFont(font1);
        label_65 = new QLabel(centralwidget);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(130, 310, 16, 21));
        label_65->setFont(font1);
        label_66 = new QLabel(centralwidget);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(170, 210, 16, 21));
        label_66->setFont(font1);
        label_67 = new QLabel(centralwidget);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(210, 160, 16, 21));
        label_67->setFont(font1);
        label_68 = new QLabel(centralwidget);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(150, 120, 16, 21));
        label_68->setFont(font1);
        label_69 = new QLabel(centralwidget);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(280, 180, 16, 21));
        label_69->setFont(font1);
        label_70 = new QLabel(centralwidget);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(370, 150, 16, 21));
        label_70->setFont(font1);
        label_71 = new QLabel(centralwidget);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(450, 190, 16, 21));
        label_71->setFont(font1);
        label_72 = new QLabel(centralwidget);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(460, 230, 16, 21));
        label_72->setFont(font1);
        label_73 = new QLabel(centralwidget);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(590, 220, 21, 21));
        label_73->setFont(font1);
        label_74 = new QLabel(centralwidget);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(560, 310, 21, 21));
        label_74->setFont(font1);
        label_75 = new QLabel(centralwidget);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(510, 380, 21, 21));
        label_75->setFont(font1);
        label_76 = new QLabel(centralwidget);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(480, 330, 21, 21));
        label_76->setFont(font1);
        label_77 = new QLabel(centralwidget);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(420, 290, 21, 21));
        label_77->setFont(font1);
        label_78 = new QLabel(centralwidget);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(360, 330, 21, 21));
        label_78->setFont(font1);
        label_79 = new QLabel(centralwidget);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(450, 360, 21, 21));
        label_79->setFont(font1);
        label_80 = new QLabel(centralwidget);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(430, 430, 21, 21));
        label_80->setFont(font1);
        label_81 = new QLabel(centralwidget);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(310, 270, 21, 21));
        label_81->setFont(font1);
        label_82 = new QLabel(centralwidget);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(270, 280, 21, 21));
        label_82->setFont(font1);
        label_83 = new QLabel(centralwidget);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(190, 290, 21, 21));
        label_83->setFont(font1);
        label_84 = new QLabel(centralwidget);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(220, 250, 21, 21));
        label_84->setFont(font1);
        label_85 = new QLabel(centralwidget);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(360, 220, 21, 21));
        label_85->setFont(font1);
        label_86 = new QLabel(centralwidget);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(410, 250, 21, 21));
        label_86->setFont(font1);
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(1180, 520, 101, 31));
        QFont font3;
        font3.setPointSize(12);
        pushButton->setFont(font3);
        label_87 = new QLabel(centralwidget);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(890, 630, 81, 21));
        label_87->setFont(font2);
        lineEdit_3 = new QLineEdit(centralwidget);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(990, 630, 113, 20));
        label_88 = new QLabel(centralwidget);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(1470, 140, 91, 21));
        label_88->setFont(font1);
        label_89 = new QLabel(centralwidget);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(1470, 110, 91, 21));
        label_89->setFont(font1);
        label_90 = new QLabel(centralwidget);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(1470, 80, 91, 21));
        label_90->setFont(font1);
        label_91 = new QLabel(centralwidget);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(1470, 50, 121, 21));
        label_91->setFont(font1);
        label_92 = new QLabel(centralwidget);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(1470, 20, 121, 21));
        label_92->setFont(font1);
        label_93 = new QLabel(centralwidget);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(1470, 620, 121, 21));
        label_93->setFont(font1);
        label_94 = new QLabel(centralwidget);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(1470, 590, 121, 21));
        label_94->setFont(font1);
        label_95 = new QLabel(centralwidget);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(1470, 530, 121, 21));
        label_95->setFont(font1);
        label_96 = new QLabel(centralwidget);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(1470, 560, 121, 21));
        label_96->setFont(font1);
        label_97 = new QLabel(centralwidget);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(1470, 170, 121, 21));
        label_97->setFont(font1);
        label_98 = new QLabel(centralwidget);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(1470, 200, 121, 21));
        label_98->setFont(font1);
        label_99 = new QLabel(centralwidget);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(1470, 230, 121, 21));
        label_99->setFont(font1);
        label_100 = new QLabel(centralwidget);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(1470, 260, 151, 21));
        label_100->setFont(font1);
        label_101 = new QLabel(centralwidget);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(1470, 290, 151, 21));
        label_101->setFont(font1);
        label_102 = new QLabel(centralwidget);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(1470, 320, 151, 21));
        label_102->setFont(font1);
        label_103 = new QLabel(centralwidget);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(1470, 350, 151, 21));
        label_103->setFont(font1);
        label_104 = new QLabel(centralwidget);
        label_104->setObjectName(QString::fromUtf8("label_104"));
        label_104->setGeometry(QRect(1470, 380, 151, 21));
        label_104->setFont(font1);
        label_105 = new QLabel(centralwidget);
        label_105->setObjectName(QString::fromUtf8("label_105"));
        label_105->setGeometry(QRect(1470, 410, 151, 21));
        label_105->setFont(font1);
        label_106 = new QLabel(centralwidget);
        label_106->setObjectName(QString::fromUtf8("label_106"));
        label_106->setGeometry(QRect(1470, 440, 171, 21));
        label_106->setFont(font1);
        label_107 = new QLabel(centralwidget);
        label_107->setObjectName(QString::fromUtf8("label_107"));
        label_107->setGeometry(QRect(1470, 470, 171, 21));
        label_107->setFont(font1);
        label_108 = new QLabel(centralwidget);
        label_108->setObjectName(QString::fromUtf8("label_108"));
        label_108->setGeometry(QRect(1470, 500, 171, 21));
        label_108->setFont(font1);
        label_109 = new QLabel(centralwidget);
        label_109->setObjectName(QString::fromUtf8("label_109"));
        label_109->setGeometry(QRect(1470, 650, 181, 21));
        label_109->setFont(font1);
        label_110 = new QLabel(centralwidget);
        label_110->setObjectName(QString::fromUtf8("label_110"));
        label_110->setGeometry(QRect(1470, 680, 181, 21));
        label_110->setFont(font1);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1704, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QString());
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_2->setText(QCoreApplication::translate("MainWindow", "Ruta 1 - 2", nullptr));
        label_3->setText(QString());
        label_4->setText(QString());
        comboBox_2->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_2->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_2->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_2->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_2->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_2->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_2->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_2->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_2->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_5->setText(QString());
        label_6->setText(QString());
        label_7->setText(QString());
        label_8->setText(QString());
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        label_12->setText(QString());
        label_13->setText(QString());
        label_14->setText(QString());
        label_15->setText(QString());
        label_16->setText(QString());
        label_17->setText(QString());
        label_18->setText(QString());
        label_19->setText(QString());
        label_20->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        label_23->setText(QString());
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QString());
        label_29->setText(QString());
        label_30->setText(QString());
        label_31->setText(QString());
        label_32->setText(QString());
        label_33->setText(QCoreApplication::translate("MainWindow", "Ruta 2-3", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Ruta 3-4", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Ruta 4-5", nullptr));
        comboBox_3->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_3->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_3->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_3->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_3->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_3->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_3->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_3->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_3->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_4->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_4->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_4->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_4->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_4->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_4->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_4->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_4->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_4->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_5->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_5->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_5->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_5->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_5->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_5->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_5->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_5->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_5->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_36->setText(QCoreApplication::translate("MainWindow", "Ruta 21-6", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Ruta 7-8", nullptr));
        comboBox_6->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_6->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_6->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_6->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_6->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_6->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_6->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_6->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_6->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_7->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_7->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_7->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_7->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_7->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_7->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_7->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_7->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_7->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_8->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_8->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_8->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_8->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_8->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_8->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_8->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_8->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_8->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_38->setText(QCoreApplication::translate("MainWindow", "Ruta 3-21", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Ruta 6-7", nullptr));
        comboBox_9->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_9->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_9->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_9->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_9->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_9->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_9->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_9->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_9->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_10->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_10->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_10->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_10->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_10->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_10->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_10->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_10->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_10->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_40->setText(QCoreApplication::translate("MainWindow", "Ruta 22-18", nullptr));
        comboBox_11->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_11->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_11->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_11->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_11->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_11->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_11->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_11->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_11->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_12->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_12->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_12->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_12->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_12->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_12->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_12->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_12->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_12->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_41->setText(QCoreApplication::translate("MainWindow", "Ruta 15-14", nullptr));
        comboBox_13->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_13->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_13->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_13->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_13->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_13->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_13->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_13->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_13->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_42->setText(QCoreApplication::translate("MainWindow", "Ruta 19-15", nullptr));
        comboBox_14->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_14->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_14->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_14->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_14->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_14->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_14->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_14->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_14->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_15->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_15->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_15->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_15->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_15->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_15->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_15->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_15->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_15->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_43->setText(QCoreApplication::translate("MainWindow", "Ruta 21-18", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Ruta 20-19", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Ruta 7-22", nullptr));
        comboBox_16->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_16->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_16->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_16->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_16->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_16->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_16->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_16->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_16->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_46->setText(QCoreApplication::translate("MainWindow", "Ruta 18-15", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "Ruta 1-20", nullptr));
        comboBox_17->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_17->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_17->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_17->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_17->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_17->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_17->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_17->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_17->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_18->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_18->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_18->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_18->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_18->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_18->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_18->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_18->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_18->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_48->setText(QCoreApplication::translate("MainWindow", "Ruta 22-23", nullptr));
        comboBox_19->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_19->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_19->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_19->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_19->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_19->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_19->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_19->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_19->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_20->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_20->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_20->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_20->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_20->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_20->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_20->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_20->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_20->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_49->setText(QCoreApplication::translate("MainWindow", "Ruta 14-9", nullptr));
        comboBox_21->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_21->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_21->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_21->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_21->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_21->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_21->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_21->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_21->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_50->setText(QCoreApplication::translate("MainWindow", "Ruta 9-10", nullptr));
        comboBox_22->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_22->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_22->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_22->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_22->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_22->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_22->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_22->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_22->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_23->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_23->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_23->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_23->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_23->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_23->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_23->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_23->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_23->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_51->setText(QCoreApplication::translate("MainWindow", "Ruta 10-11", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Ruta 9-11", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Ruta 4-6", nullptr));
        comboBox_24->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_24->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_24->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_24->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_24->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_24->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_24->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_24->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_24->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_54->setText(QCoreApplication::translate("MainWindow", "Ruta 23-8", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "Ruta 8-9", nullptr));
        comboBox_25->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_25->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_25->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_25->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_25->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_25->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_25->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_25->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_25->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_26->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_26->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_26->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_26->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_26->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_26->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_26->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_26->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_26->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_56->setText(QCoreApplication::translate("MainWindow", "Ruta 17-16", nullptr));
        comboBox_27->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_27->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_27->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_27->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_27->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_27->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_27->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_27->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_27->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_28->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_28->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_28->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_28->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_28->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_28->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_28->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_28->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_28->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_57->setText(QCoreApplication::translate("MainWindow", "Ruta 9-13", nullptr));
        comboBox_30->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_30->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_30->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_30->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_30->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_30->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_30->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_30->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_30->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        comboBox_31->setItemText(0, QCoreApplication::translate("MainWindow", "Sin pavimento 50", nullptr));
        comboBox_31->setItemText(1, QCoreApplication::translate("MainWindow", "No usar", nullptr));
        comboBox_31->setItemText(2, QCoreApplication::translate("MainWindow", "Calle nueva 10", nullptr));
        comboBox_31->setItemText(3, QCoreApplication::translate("MainWindow", "Con lluvia 20", nullptr));
        comboBox_31->setItemText(4, QCoreApplication::translate("MainWindow", "Horario pesado 30", nullptr));
        comboBox_31->setItemText(5, QCoreApplication::translate("MainWindow", "Construcciones 70", nullptr));
        comboBox_31->setItemText(6, QCoreApplication::translate("MainWindow", "Huelga 60", nullptr));
        comboBox_31->setItemText(7, QCoreApplication::translate("MainWindow", "Operativo 35", nullptr));
        comboBox_31->setItemText(8, QCoreApplication::translate("MainWindow", "Sin tr\303\241nsito 5", nullptr));

        label_60->setText(QCoreApplication::translate("MainWindow", "Ruta 12-11", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindow", "Ruta 15-17", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindow", "Ruta 16-13", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindow", "Ruta 13-12", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Cant\303\263n inicial", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "Cant\303\263n Final", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        label_66->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        label_72->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        label_73->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        label_74->setText(QCoreApplication::translate("MainWindow", "11", nullptr));
        label_75->setText(QCoreApplication::translate("MainWindow", "12", nullptr));
        label_76->setText(QCoreApplication::translate("MainWindow", "13", nullptr));
        label_77->setText(QCoreApplication::translate("MainWindow", "14", nullptr));
        label_78->setText(QCoreApplication::translate("MainWindow", "15", nullptr));
        label_79->setText(QCoreApplication::translate("MainWindow", "16", nullptr));
        label_80->setText(QCoreApplication::translate("MainWindow", "17", nullptr));
        label_81->setText(QCoreApplication::translate("MainWindow", "18", nullptr));
        label_82->setText(QCoreApplication::translate("MainWindow", "19", nullptr));
        label_83->setText(QCoreApplication::translate("MainWindow", "20", nullptr));
        label_84->setText(QCoreApplication::translate("MainWindow", "21", nullptr));
        label_85->setText(QCoreApplication::translate("MainWindow", "22", nullptr));
        label_86->setText(QCoreApplication::translate("MainWindow", "23", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Iniciar", nullptr));
        label_87->setText(QCoreApplication::translate("MainWindow", "Total", nullptr));
        label_88->setText(QCoreApplication::translate("MainWindow", "5: La cruz", nullptr));
        label_89->setText(QCoreApplication::translate("MainWindow", "4: Upala", nullptr));
        label_90->setText(QCoreApplication::translate("MainWindow", "3: Liberia", nullptr));
        label_91->setText(QCoreApplication::translate("MainWindow", "2: Santa Cruz", nullptr));
        label_92->setText(QCoreApplication::translate("MainWindow", "1: Puntarenas", nullptr));
        label_93->setText(QCoreApplication::translate("MainWindow", "21: Ca\303\261as", nullptr));
        label_94->setText(QCoreApplication::translate("MainWindow", "20: Hojancha", nullptr));
        label_95->setText(QCoreApplication::translate("MainWindow", "18: Tilaran", nullptr));
        label_96->setText(QCoreApplication::translate("MainWindow", "19: Bagaces", nullptr));
        label_97->setText(QCoreApplication::translate("MainWindow", "6: Guatuso", nullptr));
        label_98->setText(QCoreApplication::translate("MainWindow", "7: San Carlos", nullptr));
        label_99->setText(QCoreApplication::translate("MainWindow", "8: Sarapiqu\303\255", nullptr));
        label_100->setText(QCoreApplication::translate("MainWindow", "9: Sarapiqu\303\255 Sur", nullptr));
        label_101->setText(QCoreApplication::translate("MainWindow", "10: Pocos\303\255", nullptr));
        label_102->setText(QCoreApplication::translate("MainWindow", "11: Gu\303\241piles", nullptr));
        label_103->setText(QCoreApplication::translate("MainWindow", "12: Cartago", nullptr));
        label_104->setText(QCoreApplication::translate("MainWindow", "13: Coronado", nullptr));
        label_105->setText(QCoreApplication::translate("MainWindow", "14: Zarcero", nullptr));
        label_106->setText(QCoreApplication::translate("MainWindow", "15: Montes de oro", nullptr));
        label_107->setText(QCoreApplication::translate("MainWindow", "16: Santa Ana", nullptr));
        label_108->setText(QCoreApplication::translate("MainWindow", "17: Parrita", nullptr));
        label_109->setText(QCoreApplication::translate("MainWindow", "22: San Carlos Este", nullptr));
        label_110->setText(QCoreApplication::translate("MainWindow", "23: Sarapiqu\303\255 Oeste", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
