/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QLabel *label_2;
    QLabel *label;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QCheckBox *checkBox_6;
    QCheckBox *checkBox_7;
    QLabel *label_3;
    QCheckBox *checkBox_8;
    QCheckBox *checkBox_9;
    QCheckBox *checkBox_10;
    QCheckBox *checkBox_11;
    QCheckBox *checkBox_12;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QCheckBox *checkBox_13;
    QCheckBox *checkBox_14;
    QCheckBox *checkBox_15;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1107, 765);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setEnabled(true);
        checkBox = new QCheckBox(centralwidget);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(150, 140, 101, 21));
        QFont font;
        font.setFamilies({QString::fromUtf8("Gill Sans Ultra Bold")});
        font.setPointSize(12);
        checkBox->setFont(font);
        checkBox_2 = new QCheckBox(centralwidget);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(230, 190, 101, 21));
        checkBox_2->setFont(font);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setEnabled(false);
        label_2->setGeometry(QRect(150, 150, 101, 61));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/1_2.png")));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(50, 10, 972, 698));
        label->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/Sabana.png")));
        checkBox_3 = new QCheckBox(centralwidget);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(320, 250, 101, 21));
        checkBox_3->setFont(font);
        checkBox_4 = new QCheckBox(centralwidget);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(480, 400, 101, 21));
        checkBox_4->setFont(font);
        checkBox_5 = new QCheckBox(centralwidget);
        checkBox_5->setObjectName(QString::fromUtf8("checkBox_5"));
        checkBox_5->setGeometry(QRect(720, 410, 101, 21));
        checkBox_5->setFont(font);
        checkBox_6 = new QCheckBox(centralwidget);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(970, 420, 101, 21));
        checkBox_6->setFont(font);
        checkBox_7 = new QCheckBox(centralwidget);
        checkBox_7->setObjectName(QString::fromUtf8("checkBox_7"));
        checkBox_7->setGeometry(QRect(980, 670, 101, 21));
        checkBox_7->setFont(font);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setEnabled(false);
        label_3->setGeometry(QRect(240, 210, 101, 61));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/1_2.png")));
        checkBox_8 = new QCheckBox(centralwidget);
        checkBox_8->setObjectName(QString::fromUtf8("checkBox_8"));
        checkBox_8->setGeometry(QRect(740, 640, 101, 21));
        checkBox_8->setFont(font);
        checkBox_9 = new QCheckBox(centralwidget);
        checkBox_9->setObjectName(QString::fromUtf8("checkBox_9"));
        checkBox_9->setGeometry(QRect(420, 630, 101, 21));
        checkBox_9->setFont(font);
        checkBox_10 = new QCheckBox(centralwidget);
        checkBox_10->setObjectName(QString::fromUtf8("checkBox_10"));
        checkBox_10->setGeometry(QRect(440, 530, 111, 21));
        checkBox_10->setFont(font);
        checkBox_11 = new QCheckBox(centralwidget);
        checkBox_11->setObjectName(QString::fromUtf8("checkBox_11"));
        checkBox_11->setGeometry(QRect(200, 430, 111, 21));
        checkBox_11->setFont(font);
        checkBox_12 = new QCheckBox(centralwidget);
        checkBox_12->setObjectName(QString::fromUtf8("checkBox_12"));
        checkBox_12->setGeometry(QRect(270, 330, 111, 21));
        checkBox_12->setFont(font);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setEnabled(false);
        label_4->setGeometry(QRect(330, 270, 171, 141));
        label_4->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/2_3.png")));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setEnabled(true);
        label_5->setGeometry(QRect(490, 400, 231, 31));
        label_5->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/4_5 - copia.png")));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setEnabled(false);
        label_6->setGeometry(QRect(740, 410, 231, 31));
        label_6->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/4_5 - copia.png")));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setEnabled(false);
        label_7->setGeometry(QRect(970, 420, 21, 281));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/6_7.png")));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setEnabled(false);
        label_8->setGeometry(QRect(740, 650, 241, 41));
        label_8->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/7_8.png")));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setEnabled(false);
        label_9->setGeometry(QRect(420, 620, 341, 51));
        label_9->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/8_9.png")));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setEnabled(false);
        label_10->setGeometry(QRect(410, 550, 41, 111));
        label_10->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/9_10.png")));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setEnabled(false);
        label_11->setGeometry(QRect(440, 400, 51, 151));
        label_11->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/4_10.png")));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setEnabled(false);
        label_12->setGeometry(QRect(210, 430, 241, 121));
        label_12->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/10_11.png")));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setEnabled(false);
        label_13->setGeometry(QRect(210, 340, 71, 101));
        label_13->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/11_12_3.png")));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setEnabled(false);
        label_14->setGeometry(QRect(270, 250, 71, 101));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/11_12_3.png")));
        checkBox_13 = new QCheckBox(centralwidget);
        checkBox_13->setObjectName(QString::fromUtf8("checkBox_13"));
        checkBox_13->setGeometry(QRect(120, 500, 111, 21));
        checkBox_13->setFont(font);
        checkBox_14 = new QCheckBox(centralwidget);
        checkBox_14->setObjectName(QString::fromUtf8("checkBox_14"));
        checkBox_14->setGeometry(QRect(110, 370, 111, 21));
        checkBox_14->setFont(font);
        checkBox_15 = new QCheckBox(centralwidget);
        checkBox_15->setObjectName(QString::fromUtf8("checkBox_15"));
        checkBox_15->setGeometry(QRect(130, 630, 111, 21));
        checkBox_15->setFont(font);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setEnabled(false);
        label_15->setGeometry(QRect(120, 380, 101, 61));
        label_15->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/1_2.png")));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setEnabled(false);
        label_16->setGeometry(QRect(130, 630, 291, 31));
        label_16->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/9_15.png")));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setEnabled(false);
        label_17->setGeometry(QRect(120, 500, 21, 161));
        label_17->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/13_15.png")));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setEnabled(false);
        label_18->setGeometry(QRect(130, 500, 301, 131));
        label_18->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/9_13.png")));
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setEnabled(false);
        label_19->setGeometry(QRect(110, 360, 21, 161));
        label_19->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/13_15.png")));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setEnabled(false);
        label_20->setGeometry(QRect(100, 140, 61, 251));
        label_20->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/1_14.png")));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(700, 380, 21, 21));
        label_21->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(940, 390, 21, 21));
        label_22->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(690, 430, 21, 21));
        label_23->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(940, 440, 21, 21));
        label_24->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(950, 640, 21, 21));
        label_25->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(420, 490, 21, 21));
        label_26->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(480, 600, 21, 21));
        label_27->setPixmap(QPixmap(QString::fromUtf8("../Imagenes/casa.png")));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(180, 190, 21, 16));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Franklin Gothic Book")});
        font1.setPointSize(14);
        label_28->setFont(font1);
        label_28->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(260, 250, 21, 16));
        label_29->setFont(font1);
        label_29->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(410, 310, 21, 16));
        label_30->setFont(font1);
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(310, 310, 21, 16));
        label_31->setFont(font1);
        label_31->setAlignment(Qt::AlignCenter);
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(250, 400, 21, 16));
        label_32->setFont(font1);
        label_32->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(590, 430, 21, 16));
        label_33->setFont(font1);
        label_33->setAlignment(Qt::AlignCenter);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(850, 440, 21, 16));
        label_34->setFont(font1);
        label_34->setAlignment(Qt::AlignCenter);
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(930, 560, 21, 16));
        label_35->setFont(font1);
        label_35->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(860, 630, 21, 16));
        label_36->setFont(font1);
        label_36->setAlignment(Qt::AlignCenter);
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(600, 610, 21, 16));
        label_37->setFont(font1);
        label_37->setAlignment(Qt::AlignCenter);
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(450, 590, 21, 16));
        label_38->setFont(font1);
        label_38->setAlignment(Qt::AlignCenter);
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(490, 490, 21, 16));
        label_39->setFont(font1);
        label_39->setAlignment(Qt::AlignCenter);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(320, 460, 21, 16));
        label_40->setFont(font1);
        label_40->setAlignment(Qt::AlignCenter);
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(260, 550, 21, 16));
        label_41->setFont(font1);
        label_41->setAlignment(Qt::AlignCenter);
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(260, 650, 21, 16));
        label_42->setFont(font1);
        label_42->setAlignment(Qt::AlignCenter);
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(150, 570, 21, 16));
        label_43->setFont(font1);
        label_43->setAlignment(Qt::AlignCenter);
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(90, 440, 21, 16));
        label_44->setFont(font1);
        label_44->setAlignment(Qt::AlignCenter);
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(120, 260, 21, 16));
        label_45->setFont(font1);
        label_45->setAlignment(Qt::AlignCenter);
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(160, 430, 21, 16));
        label_46->setFont(font1);
        label_46->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralwidget);
        label->raise();
        label_2->raise();
        label_3->raise();
        checkBox_2->raise();
        label_5->raise();
        label_6->raise();
        checkBox_5->raise();
        label_7->raise();
        checkBox_6->raise();
        label_8->raise();
        checkBox_7->raise();
        label_9->raise();
        checkBox_8->raise();
        label_10->raise();
        checkBox_9->raise();
        label_11->raise();
        label_12->raise();
        checkBox_10->raise();
        label_13->raise();
        label_4->raise();
        label_14->raise();
        checkBox_12->raise();
        checkBox_4->raise();
        checkBox_3->raise();
        label_15->raise();
        checkBox_11->raise();
        label_16->raise();
        label_17->raise();
        checkBox_15->raise();
        label_18->raise();
        label_19->raise();
        checkBox_13->raise();
        label_20->raise();
        checkBox_14->raise();
        checkBox->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        label_46->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1107, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        checkBox->setText(QCoreApplication::translate("MainWindow", "Torre 1", nullptr));
        checkBox_2->setText(QCoreApplication::translate("MainWindow", "Torre 2", nullptr));
        label_2->setText(QString());
        label->setText(QString());
        checkBox_3->setText(QCoreApplication::translate("MainWindow", "Torre 3", nullptr));
        checkBox_4->setText(QCoreApplication::translate("MainWindow", "Torre 4", nullptr));
        checkBox_5->setText(QCoreApplication::translate("MainWindow", "Torre 5", nullptr));
        checkBox_6->setText(QCoreApplication::translate("MainWindow", "Torre 6", nullptr));
        checkBox_7->setText(QCoreApplication::translate("MainWindow", "Torre 7", nullptr));
        label_3->setText(QString());
        checkBox_8->setText(QCoreApplication::translate("MainWindow", "Torre 8", nullptr));
        checkBox_9->setText(QCoreApplication::translate("MainWindow", "Torre 9", nullptr));
        checkBox_10->setText(QCoreApplication::translate("MainWindow", "Torre 10", nullptr));
        checkBox_11->setText(QCoreApplication::translate("MainWindow", "Torre 11", nullptr));
        checkBox_12->setText(QCoreApplication::translate("MainWindow", "Torre 12", nullptr));
        label_4->setText(QString());
        label_5->setText(QString());
        label_6->setText(QString());
        label_7->setText(QString());
        label_8->setText(QString());
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        label_12->setText(QString());
        label_13->setText(QString());
        label_14->setText(QString());
        checkBox_13->setText(QCoreApplication::translate("MainWindow", "Torre 13", nullptr));
        checkBox_14->setText(QCoreApplication::translate("MainWindow", "Torre 14", nullptr));
        checkBox_15->setText(QCoreApplication::translate("MainWindow", "Torre 15", nullptr));
        label_15->setText(QString());
        label_16->setText(QString());
        label_17->setText(QString());
        label_18->setText(QString());
        label_19->setText(QString());
        label_20->setText(QString());
        label_21->setText(QString());
        label_22->setText(QString());
        label_23->setText(QString());
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QString());
        label_28->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
